Replace backstop with lostpixel.

diff --git a/.platform.app.yaml b/.platform.app.yaml
--- a/.platform.app.yaml
+++ b/.platform.app.yaml
@@ -115,11 +115,22 @@ hooks:
 
 
     # We run deploy hook after your application has been deployed and started.
+    # We use set -e to cause a total fail if something goes wrong.
+    # Otherwise, a deploy-status file will instead be populated with 1.
+    # You can use a Github action to check if there was any issues with deploy.
+    # This is necessary, as PlatformSH just fails silently, such as when
+    # the Drupal config is invalid.
     deploy: |
-      cd web
-      drush -y cache-rebuild
-      drush -y updatedb
-      drush -y config-import
+      STATUS_FILE="$PLATFORM_DOCUMENT_ROOT/sites/default/files/deploy-status"
+      rm -f "$STATUS_FILE"
+      echo "0" > "$STATUS_FILE"
+      set -e
+      cd "$PLATFORM_DOCUMENT_ROOT"
+      if [ "$PLATFORM_BRANCH" != "master" ]; then
+        drush user:password testeditor testeditor
+      fi
+      drush --yes deploy
+      echo "1" > "$STATUS_FILE"
 
 # The configuration of scheduled execution.
 crons:
